export default {
    SET_QUADRAS_LOGRADOUROS: 'SET_QUADRAS_LOGRADOUROS',
    ADD_QUADRAS_LOGRADOUROS: 'ADD_QUADRAS_LOGRADOUROS',
    UPDATE_QUADRAS_LOGRADOUROS: 'UPDATE_QUADRAS_LOGRADOUROS',
    DESTROY_QUADRAS_LOGRADOUROS: 'DESTROY_QUADRAS_LOGRADOUROS'
};
