export default {
    TO_DARK_STATUSBAR: 'TO_DARK_STATUSBAR',
    TO_LIGHT_STATUSBAR: 'TO_LIGHT_STATUSBAR',
    OPEN_INTERVENTIONAL_MODAL: 'OPEN_INTERVENTIONAL_MODAL',
    CLOSE_INTERVENTIONAL_MODAL: 'CLOSE_INTERVENTIONAL_MODAL'
};
